name: tests
on: [push, pull_request]
jobs:
  tests:
     runs-on: ${{ matrix.os }}
     strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version:
            - "3.5"
            - "3.6"
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10-dev"
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r test-requirements.txt
        - name: run tests
          run: pytest paver/
